### PR TITLE
Create Pull Request Labeler

### PR DESCRIPTION
**Pull request by soumitradev**
Add an automated pull request labeler that labels pull requests automatically using [GitHub Actions](https://github.com/features/actions).

This script runs every time a Pull Request is made to the repo, and labels the Pull Requests according to the files the Pull Request changes.

### CODE REVIEW

**Comment by sambitdash** [comment]
I am not sure why is this really needed. We use label based on a release for the project and not based on PRs with PDFIO.

**Comment by soumitradev** [comment]
Hi! This was actually a task for Google Code-in, and I chose this repo to add this labeler to. More info here: https://codein.withgoogle.com/dashboard/task-instances/5893132659458048/. It's fine if you don't need the labeler though!

**Comment by sambitdash** [comment]
@soumitradev I appreciate your work. But, I am still not convinced how we will be using this and how it fits into the Julia package ecosystem. Till that point while I will keep the PR open and merge when I really understand benefits of it.

**Comment by soumitradev** [comment]
Hi, according to the mentor for this task, the PR need not be merged. If you don't require this addition, you can go ahead and close this PR. Sorry if this disturbed your workflow.

**Comment by logankilpatrick** [comment]
@sambitdash  For high volume/velocity repos, this is nice as it gives a quick indicator as to what the content is about without you having to dig into the details. It also allows other maintainers/contributors to filter things out that they don't want to/aren't able to contribute to. 

This also is not related to the Julia Package ecosystem and rather is designed as a collaboration and productivity tool to be used on GitHub.

**Comment by soumitradev** [comment]
>Note that the words in quotes in the labeler.yml file correspond to the labels here: https://github.com/sambitdash/PDFIO.jl/labels

I'm going ahead and closing this PR since the current Pull Request labels are not file-based, and also because @sambitdash doesn't really need this labeler on this repo. @logankilpatrick I'll go work on another package instead of adding an issue to add the file-based labels.

@sambitdash Again, sorry for the noise.

**Pull request closed without merging**
