### PR TITLE
Fix for font unicode character map where glyph is of the format /uniXXXX

### LINKED ISSUE #101: Part of AGL specification not implemented
I tried to run pdPageExtractText on the pdf located:
https://www.gov.im/media/1360682/isle-of-man-inflation-report-november-2021.pdf

However, every character of the text was being interpreted as "\0"

After much pain and effort trailing through the PDFIO code, I have identified the problem as being what is returned by the fum function in PDFont.  In particular when the cn"Encoding" object contains a /Differences object with values such as /uni0047 which just represent the unicode character U+47 ('p').  Since the AGL_Glyph_To_Unicode dictionary (not sure where this comes from) doesn't contain the simple unicode mappings then the zero(Char) is returned instead.

One solution might be to just compare the /uni0047 to the base encoding dictionary and if the 0x0047 part exists then add a dictionary entry.  Another solution would be to add all of the standard unicode characters that already exist in your base encoding such as /uni0047 to the AGL_Glyph_To_Unicode dictionary.

I have made the assumption, when suggesting this solution, that the cn"Encoding" object is taken directly from the pdf file and not further processed.

If you'd like me to try to create a pull request,  I'd be happy to, but I thought I'd ask first in case your more holistic view of the project leads to a more effective solution.

### PR DESCRIPTION
**Pull request by dannywinrow**
fixes #101

### CODE REVIEW

**Comment by sambitdash** [comment]
@dannywinrow, 

Thank you for your submission. 

Unfortunately, your submission is not compliant with PDF specifications. While creators can use any logic to name dictionary keys, the same cannot be incorporated into the reader. We will review the file to find if there are other font information in the file that we have overlooked in the implementations.

**Comment by dannywinrow** [comment]
Hi Sambitdash, I think you are mistaken.  The part which you have failed to implement is the correct AGL specification which you can find here https://github.com/adobe-type-tools/agl-specification

Look at section 2 and you will find this:

"Otherwise, if the component is of the form ‘uni’ (U+0075, U+006E, and U+0069) followed by a sequence of uppercase hexadecimal digits (0–9 and A–F, meaning U+0030 through U+0039 and U+0041 through U+0046), if the length of that sequence is a multiple of four, and if each group of four digits represents a value in the ranges 0000 through D7FF or E000 through FFFF, then interpret each as a Unicode scalar value and map the component to the string made of those scalar values."

**Comment by sambitdash** [comment]
@dannywinrow,

Thanks for finding the complete AGFN specification. If you are comfortable implementing the complete specification with test cases feel free to resubmit the PR with all the details. I will be happy to merge it.

**Comment by dannywinrow** [comment]
It would take significantly more work to include the full AGL specification, since a glyph name can refer to a string of characters as well as an individual unicode character.  However, the Dictionary currently used for extracting text is a CosName to Char dictionary.

As I'm not an experienced programmer I don't think I'd be able to achieve this.  I have added support in my own fork for single character /uni and /u glyphs and will just leave the issue open for now.

This pull request will not satisfy what is needed for the full AGL specification and so I am closing it.  Thanks.

**Pull request closed without merging**
